# Generated by Django 5.0.2 on 2024-04-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='balanceAfter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
